### ISSUE TITLE
prepare_gaussian_state doesn't produce exact eigenvectors for quadratic Hamiltonian

### ISSUE THREAD

**Issue by warrenalphonso** [quantumlib/OpenFermion-Cirq#407]
Here's a [notebook](https://github.com/warrenalphonso/qc-mentorship/blob/master/prepare_gaussian_state.ipynb) that reproduces the issue. 

I've got a Hubbard Hamiltonian with a known ground state. I want to find the eigenvector of the tunneling term that has highest fidelity with the true ground state, so I convert the tunneling Hamiltonian to a scipy.sparse operator and find its eigenvectors (similar to how `openfermion.get_ground_state` does it). Then I calculate fidelity with the true ground state and choose the vector with highest fidelity. The highest fidelity is about 0.20.

I also tried perturbing the tunneling term with the interaction term, and then repeating the above procedure. The highest fidelity is now about 0.99. 

Then I find the tunneling eigenvector closest to the above perturbed eigenvector. 

Now, I want to get the circuit to produce this eigenvector, so I use `openfermioncirq.prepare_gaussian_state` and try all `occupied_orbitals` subsets that sum to the correct eigenvalue. I expect to be able to perfectly produce my chosen tunneling eigenvector, but when I use `cirq.final_wavefunction` on the Circuit outputted and compute the fidelity with the desired eigenvector, I get a max fidelity of about 0.20! 

Instead if I do the above, but compute the fidelity with the best perturbed eigenvector, I get a fidelity of 0.99. 

What's going on? I chose a tunneling Hamiltonian eigenvector, and then computed the circuit for each of the tunneling eigenvectors, and I'm not able to get large overlap for any of them. This is a quadratic Hamiltonian, so I expected an exact solution.

**Comment by kevinsung** [comment]
The issue is that you aren't creating states with the correct symmetries. The first thing to note here is that the ground state of your Hubbard Hamiltonian is an eigenvector of the total number operator, with eigenvalue 2. You can create the total number operator and check this like this:
```
num = openfermion.get_sparse_operator(openfermion.number_operator(8))
print(openfermion.expectation(num, v_hub))
print(openfermion.variance(num, v_hub))
```
This gives an expectation of 2 and a variance of 0, which verifies my claim above. Now, in your notebook, in the line
```
w_tun, v_tun = scipy.sparse.linalg.eigsh(tun_sparse, k=np.shape(tun_sparse)[0]-2, which='SA')
```
where you get eigenvectors of the tunneling term, this call to the Scipy eigenvector routine does not return eigenvectors with the correct symmetry, i.e., they don't have a fixed particle number of 2. One method I find that often fixes this issue is to pass in an initial guess with the correct symmetry:
```
v0 = openfermion.jw_configuration_state([0, 1], 8)
w_tun, v_tun = scipy.sparse.linalg.eigsh(tun_sparse, v0=v0, k=np.shape(tun_sparse)[0]-2, which='SA')
```
Now this actually outputs an eigenvector that has overlap 0.977 with the Hubbard ground state. This also fixes the issues in the rest of the notebook. Note that `openfermioncirq.prepare_gaussian_state` always produces states with a fixed particle number (the number of orbitals that are filled).
